### ISSUE TITLE
Some fixes in french localization file, and some remark about localization in general

### ISSUE THREAD

**Issue by LaurentGrenet** [sylikc/jpegview#105]
Hi,
following its update in last rev, I carefully reviewed the strings_fr.txt file... and I discovered that several entries inside were invalid (and were already invalid before the update), since in these entries, original text and its translation aren't delimited by a <tab>, as they should, but rather by a simple space. As a result, these entries are obviously ignored.
Going forward in my investigations, I also discovered that the list of translations.... is not exactly the same in all translations files ! 
This makes very difficult to keep these files up-to-date. 

**As a result, it would be great if you could provide us with an "official list"** of all strings needing translation (and **removing all strings that "historically" needed one, but do not exist any more**, if any).

In the meantime, I provide you (here attached [strings_fr.txt](https://github.com/sylikc/jpegview/files/10344962/strings_fr.txt)) with an updated french translation file, in which I have fixed the errors mentioned above, and added some missing translations. Sorry to have done that just after the last update, I agree it would have been better to provide it just BEFORE...
And last but not least, I wanted to provide this file as a "Pull request", but since I've not been able to create a new PR, i'm using the "Issue" way to send it, even if I know that i is not the"right way of doing"....

**Comment by sylikc** [comment]
PRs aren't easy to figure out lol.  I'll credit you with the translation regardless.

> As a result, it would be great if you could provide us with an "official list" of all strings needing translation (and removing all strings that "historically" needed one, but do not exist any more, if any).

I noticed this as well when I was fixing the FR translation... there's quite a bit of things which are outdated, and no one file is the same... this goes hand in hand with the INI problems that JPEGView has... 

In the coming weeks or so, I'm going to try to get restarted on #60 as this also affects localization of the INI file, and I'll take a look at the strings_XX.txt files

**Comment by sylikc** [comment]
Fixed by commit 5be423a0df9f8d38c183fa38c26240943ca017f4 which now has an autogenerated strings.txt file which is up-to-date with source
