### ISSUE TITLE
Device profile to reference when color management is enabled

### ISSUE THREAD

**Issue by lascases** [sylikc/jpegview#111]
When writing "UseEmbeddedColorProfiles=true" in the ini file and enabling GDI+ drawing and color management,
Instead of Profiles associated with this device on the Device tab, "Windows Color System Defaults" is referred to the device profile (Profile for converting the RGB values of the image to RGB values that match the monitor and outputting them) .
Is this the spec?

**Comment by lascases** [comment]
I'm sorry.

i was using a different old version
When I tried it now, the behavior was slightly different, so I don't really know what kind of behavior it is now.

Therefore, if possible, could you please delete this issue?

**Comment by sylikc** [comment]
Test the current behavior, and if it still isn't quite working the way you'd expect, you can report back :)
