### ISSUE TITLE
The file can't be read. JXL decoding requires the Microsoft Visual C++ Redistributable.

### ISSUE THREAD

**Issue by Ktr4ks** [sylikc/jpegview#118]
I keep getting this error, even though I already have this installed, I even reinstalled it, but the problem still persists. I'm using Windows 10.

**Comment by qbnu** [comment]
That message shows up whenever a JXL file fails to load, I need to make it more specific. Are you sure the file is valid?

**Comment by Ktr4ks** [comment]
I've tried multiple files that were converted to jxl through squoosh.app, the same files can be opened without problems in qimgv.

**Comment by sylikc** [comment]
> I've tried multiple files that were converted to jxl through squoosh.app, the same files can be opened without problems in qimgv.

@Ktr4ks please post a file which opens in qimgv and doesn't open in JPEGView so we can take a look at it.

**Comment by Ktr4ks** [comment]
> @Ktr4ks please post a file which opens in qimgv and doesn't open in JPEGView so we can take a look at it.
Sure, I also had success with it in Irfanview.
https://files.catbox.moe/wlnvra.jxl

**Comment by qbnu** [comment]
@sylikc The MSI installer doesn't include the JXL dlls.

**Comment by sylikc** [comment]
> @sylikc The MSI installer doesn't include the JXL dlls. 

Whoops

**Comment by sylikc** [comment]
aside from the MSI installer to include the JXL dlls, the messaging should be more consistent with commit d013748445321a95a787528572b39342fae7f8bf

**Comment by sylikc** [comment]
v1.1.43 has been tested to include all DLLs... at least I tried to be more thorough with my testing after botching v1.1.42 release

**Comment by marcusdoc** [comment]
Fresh install of Windows 11 OS and getting the error "Decoding this format requires the Microsoft Visual C++ Redistributable"
Used the JPEGView64_en-us_1.3.46.msi installer
 
 What version of the Visual C++ redistributable is required?
 
 note: I did do an unattended.xml installation of Windows 11 to remove the MS bloatware so maybe there was some app that was removed that contained the Visual C++ files.

**Comment by qbnu** [comment]
@marcusdoc https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
