### ISSUE TITLE
ShowFullScreen=false aka windowed mode should be the default setting (or auto, at least)

### ISSUE THREAD

**Issue by Pentaphon** [sylikc/jpegview#122]
I have to change this on every new machine I install jpegview on and most people I see using it have to change it as well. 

"auto" would also be better than "true" being the default.

**NOW YOU CAN VOTE FOR WHICH YOU PREFER TO BE THE DEFAULT HERE: https://github.com/sylikc/jpegview/discussions/125**

**Comment by Pentaphon** [comment]
> I would have to start a poll to really figure out how people are using this.

Please do.

**Comment by sylikc** [comment]
> most people I see using it have to change it as well.

can you link me to the forum or a thread where people are discussing having to change this setting or other settings?

**Comment by Pentaphon** [comment]
> can you link me to the forum or a thread where people are discussing having to change this setting or other settings?

This is from personal experience with people I know who I've converted to it.  We can always do a poll with Github discussions. I've made one here: 

https://github.com/sylikc/jpegview/discussions/125

**Comment by sylikc** [comment]
i've pinned an issue along with your poll to that issue in #140.  Closing this issue as duplicate.  Thanks
