### ISSUE TITLE
1.1.43: heic files doubled when browsing a folder

### ISSUE THREAD

**Issue by kiawizard** [sylikc/jpegview#147]
Hi! New version 1.1.43 has a bug: when I open a photo from a folder with **680** photos, jpegview shows 1/**1325**. This is because 635 of 680 are heic, and other 35 are jpeg. 35+635*2 = 1325. The actual image on the screen changes every second time I press right arrow. Version 1.1.40 did not have this issue

**Comment by sylikc** [comment]
HEIC support was added in 1.1.43.

I just did a quick test, dropped 2 HEIC pics and 1 jpeg... I didn't see that behavior.

Did you put HEIC into your INI as loaded by WIC or something?  Can you post your INI file?

**Comment by kiawizard** [comment]
You're exactly right,

FilesProcessedByWIC=*.wdp;*.hdp;*.jxr;*.heic;*.heif

I have removed *.heic;*.heif and folder browsing is now all right. So the issue seems to be like "when 2 decoders can open the same file, it is doubled"

**Comment by sylikc** [comment]
yeah, that's just sort of the way it works... both loads the image.
