### ISSUE TITLE
UseEmbeddedColorProfiles=true not working for WebP images

### ISSUE THREAD

**Issue by zcsbldm** [sylikc/jpegview#148]
Currently this only work for JPEG and TIFF images, is it possible to also use icc profile for webp images?

**Comment by zcsbldm** [comment]
When I open the webp image in my browser, it can display the image correctly.

**Comment by sylikc** [comment]
please upload an image to test against... but I'm also sure that feature isn't implemented yet... I'd put this into the backlog but at least have a specific image with an ICC profile to test against in the future 😎

**Comment by zcsbldm** [comment]
Here's 2 images for tests, they all have same icc profile, but looks quite different in jpegview.

jpg file https://ibb.co/qsSxCMf
webp file https://ibb.co/n3yDZmX

files will expire in one month.

**Comment by sylikc** [comment]
ok, i'll save it for the future.  thanks!
