### ISSUE TITLE
Want to change the default shortcut for the selector to CTRL + MouseL

### ISSUE THREAD

**Issue by vvyoko** [sylikc/jpegview#15]
Currently the left button is often pressed by mistake
And Ctrl +MouseL is itself a selection shortcut when zooming in

https://github.com/sylikc/jpegview/issues/5
And you can use the left click to move the window if this issues can be implemented
This will unify the operational logic

Left-click to move the picture while zoomed in
Left click to move the window position under normal conditions

Both magnification and normal conditions
Ctrl+MouseL are both selectors

As I am not a programmer
At the moment I can only forcibly disable the entire selector
The logic in there is really confusing

Then report a bug
“if (fileSize >= 1024 * 1024 * 100) ” should be “if (fileSize >= 1024 * 1024 ) ”
This will display properly as MB

https://github.com/sylikc/jpegview/blob/2bd00981717fb5c1cec0291cfdfbf26e975b61c0/JPEGView/Helpers.cpp#L905

**Comment by vvyoko** [comment]
https://github.com/sylikc/jpegview/blob/2bd00981717fb5c1cec0291cfdfbf26e975b61c0/JPEGView/DesktopWallpaper.cpp#L22

 needsFitToScreen ? _T("6") 
needsFitToScreen  in win10 (dont khow others) should be
needsFitToScreen ? _T("10")

**Comment by sylikc** [comment]
Just as an FYI, I addressed the zooming-in-on-accident with a new feature recently.  #106 .  It will be in the next release.

**Comment by sylikc** [comment]
100 MB bug fixed in 976af322
