### ISSUE TITLE
JPEGview freezes when moving zoomed image

### ISSUE THREAD

**Issue by IPeluchito** [sylikc/jpegview#153]
1. Open image with JPEGview.
2. Enlarge image with mouse wheel.
3. Move the enlarged image with the mouse.
4. JPEGview freezes.

Windows 11 build 22000.1516
GTX 1660Ti - 3840x2160 - 300% scaling

**Comment by sylikc** [comment]
Can you post a sample image?  How far % is it enlarging before freezing?

This could be related to #10 if your image is really big... you can try manually setting your `CPUType` and report back.

**Comment by IPeluchito** [comment]
JPEGView crashes with any image of any size and it happens exactly when the image is enlarged much more than the window size and from there you try to move the whole image with the mouse....

I can confirm that using CPUType=SSE or HighQualityResampling=false fixes the problem...

**Comment by sylikc** [comment]
This seems to specifically happen with certain types of hardware/driver or something.

Maybe it's a scaling thing, or something.  I have an AVX2-capable processor, and it doesn't crash or freeze for me.

* How much % are you zooming into before panning?  More than 1600%?  (I'm just checking if it's related to a recent change)

For now, the workaround is to set it `CPUType=SSE` ... there's something with the AVX2 routines that freezes on specific cases.  I can't seem to reproduce the freeze.

**Comment by IPeluchito** [comment]
https://user-images.githubusercontent.com/64821708/222285610-fc7ece1b-7433-4716-8b41-59b1d437cf04.mp4

The problem is present even in another fork of **JPEGView** (https://github.com/annh9b/JPEGView-Image-Viewer-and-Editor)

**i7 9700 / 16Gb RAM / GTX 1660Ti 6Gb / Win 11**

**Comment by sylikc** [comment]
(I've removed your link... that fork had a history previously of copying code without giving attribution... doesn't add any code and releases it in a really sketchy way.  See #31 .  If you look at that fork's commit history, it's strictly a copy of code and "updating" of some rogue site... which doesn't even exist anymore)

I see... nice to see it up close.  This happens to JPEGview out of the box?  No other modifications to the INI file right?

**Comment by sylikc** [comment]
Can you try the suggestion here?

https://github.com/sylikc/jpegview/issues/53#issuecomment-1164165618
> Right click the exe, go to properties, then the compatibility tab, and click on "Change High DPI settings." From there, check the box for "Override high DPI scaling behavior" and select "System" from the drop-down box

**Comment by IPeluchito** [comment]
Tested with System and System (Enhanced)...the problem is not displayed but the fonts and images in the program are pixelated...

**Comment by sylikc** [comment]
So it might be an interaction with HiDPI

**Comment by IPeluchito** [comment]
If you have a 4K TV you could connect it there... At a resolution of 3840x2160 Windows scales to 300%

**Comment by sylikc** [comment]
Ok, I can confirm I can get it to freeze when the resolution is 3840x2160, but it doesn't happen in 2880x1800.  

**I traced the code and it's definitely caused by the UpSampling AVX code.  I plan to "fallback" to SSE2 when the monitor dimensions are set a certain way as a workaround**... but I'm trying to find where exactly the limits are... 

So it's not a HiDPI thing... it's an absolute resolution thing.  I tried different scaling, and that it'll still crash at 100% scaling with 3840x2160

@IPeluchito what other resolutions are valid for you between those two above.  I'm having trouble simulating other resolutions on my environment.  If you can test other resolutions out and see if which ones cause freezing and which ones don't, that'd be helpful, thanks!

**Comment by sylikc** [comment]
The funny thing is that this only happens in the Release build and not in the Debug build...

**Comment by sylikc** [comment]
@IPeluchito can you test the latest development snapshot and see if the workaround that I put in fixes the freezing?

Download the latest 64-bit dev snapshot https://github.com/sylikc/jpegview/wiki/Dev-Snapshots#links and report back, thanks!

**Comment by IPeluchito** [comment]
Fixed !!! however I have just found another bug even present in previous versions of JPEGView and it is that if you reduce the image with the mouse to less than 0% and then enlarge it sometimes it gets stuck at 0%

**Comment by sylikc** [comment]
quite possible that there's a bug in that regard... might be related to the other zoom bug that came up #158 where the calculations get funky after unbounding the zoom.

it could be specific to having a high res display as well.  Let me update the calculations and push out a dev release for you to test

**Comment by sylikc** [comment]
I'm going to create a new issue with the text

**Comment by sylikc** [comment]
v1.2.45 has been released that fixes this issue.
