### ISSUE TITLE
whether single instance mode is supported

### ISSUE THREAD

**Issue by ouyang7923** [sylikc/jpegview#155]
as the title suggests

**Comment by pureby** [comment]
Yes, there is a setting for it in `JPEGView.ini` file. It is located in `%APPDATA%\JPEGView\JPEGView.ini` (you can copy/paste this is File Explorer address field).

If the folder does not exist, just open any image in JPEGView, right click it and go to _Settings/Admin > Edit user settings._

Now close JPEGView app. Inside the file, use Ctrl+F to find the line `SingleInstance=false` and change it to `SingleInstance=true`. Done!
