### ISSUE TITLE
1.1.44 Use the spacebar to return zoom get a smaller window（window mode）

### ISSUE THREAD

**Issue by rcyggdra** [sylikc/jpegview#158]
the previous version didn't have this problem.

**Comment by sylikc** [comment]
There was a change in this version that might have affected this behavior.  Can you post your INI and a test image?  Explain the exact steps to reproduce the unexpected behavior, and explain what's supposed to happen.

I don't quite understand what behavior is not working.  Thanks

**Comment by rcyggdra** [comment]
![Snipaste_2023-03-02_15-28-26](https://user-images.githubusercontent.com/8652464/222360507-22b16692-c139-4ddb-89de-8808401af361.png)
Press Spacebar 2 times

**Comment by sylikc** [comment]
can you post the actual image, and your INI file?  that would help, thanks.

**Comment by Ktr4ks** [comment]
I came here because of this problem

**Comment by sylikc** [comment]
@Ktr4ks can you post your INI and a sample image so I can test what changed in the last version that caused the new behavior?  I tried testing and it doesn't happen for me, but my INI might be different

**Comment by Ktr4ks** [comment]
@sylikc sure
[ini.zip](https://github.com/sylikc/jpegview/files/10874605/ini.zip)

**Comment by sylikc** [comment]
Thanks for the files @Ktr4ks ... i can reproduce the behavior and will investigate...

**Comment by sylikc** [comment]
I've investigated and it appears to be a bad interaction with the unbounding of the zoom.  Looking into a fix...

**Comment by sylikc** [comment]
A new version will be available soon with the fix.  Thanks for finding, reporting, and providing samples to help with the bugfix!
