### ISSUE TITLE
Feature request: Display HEIC Metadata

### ISSUE THREAD

**Issue by ningxia2022** [sylikc/jpegview#167]
希望能读取heic格式的图片信息，现在读取不了heic格式的拍摄日期、拍摄相机以及地理位置等
图片信息希望能移动，谢谢啦

**Comment by sylikc** [comment]
Currently it doesn't read the metadata, but I'll put it on the feature request list.  I don't know if it'll be hard to implement, but I'll investigate it.  libheif does support reading EXIF on the files.

**Comment by sylikc** [comment]
closed by #213 , included in 1.3.46 release
