### ISSUE TITLE
Support for .jfif format

### ISSUE THREAD

**Issue by JRHille** [sylikc/jpegview#168]
Hello,

I managed to make the program open the .jfif format just by associating the format to the program, it opens normally when clicking on a .jfif image. But I am not able to make the program recognize some .jfif image when in a folder. For example I open a folder that contains .jpg images along with .jfif images, and when browsing through the images within the program only the .jpg are displayed.

Would there be any modifications in the registry or in the program files for me to modify so that it also recognizes the .jfif?

Thanks

**Comment by sylikc** [comment]
`jfif` is supported but it's not on the extension list by default.

Add to `FilesProcessedByWIC=`  `*.jfif` separate entries by semi-colon.

**Comment by JRHille** [comment]
> Add to `FilesProcessedByWIC=` `*.jfif` separate entries by semi-colon.

nice, works. Thank you
