### ISSUE TITLE
Feature Request or Bug Report? Animated WebP images don't work.

### ISSUE THREAD

**Issue by Trahloc** [sylikc/jpegview#182]
Animated WebP images are significantly smaller than gifs. The good old dancing-banana.gif is 84.9KB while dancing-banana.webp is 4.15 KB.
[dancing-banana.zip](https://github.com/sylikc/jpegview/files/11084616/dancing-banana.zip)
Much appreciated if you can add this when you're able, thank you.

**Comment by sylikc** [comment]
I'll take a look to replicate this next week and see if it's a bug in JPEGView or the underlying webp library.

**Comment by qbnu** [comment]
Which version are you using?

**Comment by Trahloc** [comment]
I just snagged the latest version and it works with 1.4.25.0. Weird, I had just installed the latest version before submitting my report but failed to double check it was actually using that version vs the old one. My bad, sorry about that.
