### ISSUE TITLE
AVIF does not support HDR?

### ISSUE THREAD

**Issue by mx4994** [sylikc/jpegview#183]
I use this https://raw.githubusercontent.com/AOMediaCodec/av1-avif/master/testFiles/Netflix/avif/hdr_cosmos12920_cicp9-16-9_yuv444_full_qp10.avif image test is not working, browser is fine.

see feedback on this https://github.com/AOMediaCodec/av1-avif/issues/186

**Comment by qbnu** [comment]
Yes, currently only ICC profiles are implemented. Proper color management seems fairly complex (even Firefox still doesn't do it correctly).
https://github.com/chromium/chromium/blob/main/third_party/blink/renderer/platform/image-decoders/avif/avif_image_decoder.cc

**Comment by G2G2G2G** [comment]
@mx4994 almost nothing does, looking at avif & jxl I'd say we're a good 5 years away from all their features being supported (sadly av2 probably be getting added by then)

**Comment by sylikc** [comment]
thanks for the investigations, I've referenced this into known issues.
