### ISSUE TITLE
Suggestion - Disable crop on click+drag

### ISSUE THREAD

**Issue by JLuke73** [sylikc/jpegview#186]
The default behavior of several other apps (e.g. Windows Photo Viewer) is to have click+drag move/copy the _file_ to another location, (e.g. drag into a browser to upload on a website). Looking through KeyMap and the code, it doesn't look like this is possible in JPEG view. This would be a useful feature.

**Comment by sylikc** [comment]
Hi! This is already implemented. Look at the DefaultSelectionMode option in the ini

**Comment by JLuke73** [comment]
I must be blind, but I'm not seeing it in my ini file (attached as .txt). I'm using JPEGView 1.2.45.0 (64-bit Windows install).
[JPEGView.txt](https://github.com/sylikc/jpegview/files/11244828/JPEGView.txt)
