### ISSUE TITLE
Unable to open high-resolution .png image

### ISSUE THREAD

**Issue by AlphatoBeta** [sylikc/jpegview#187]
**Description:** Once the image resolution is too large, it is almost impossible to open it. For example, the following image parameters:
Resolution: 91311 * 25167; Bit depth: 24; Size: 337MB.
**Comparison test:** The Windows 11 image viewer can view large images normally.
**Problem recurrence rate:** 100%
_My image cannot be uploaded because it contains privacy information. Developers can use software such as PS or GIMP or Inkscope to generate similar high-resolution images for development testing_

**Comment by sylikc** [comment]
Hi, this is a known issue and an internal limitation in JPEGView.  Any images bigger than `65535` on any edge will cause issues.  If you turn `HighQualityResampling` off, there are some images which will open with minimal corruption, but this is currently a hard limitation which is not planned for a fix at this time.

Referenced here #141

The known issues pinned issue #142 also references this

**Comment by jonatino** [comment]
@sylikc I have a 13,056x45,568px that can't be opened due to "Not enough memory available". This is less than the 65k limit. It is a render of a game map. (1.9mb)

![img-3](https://github.com/sylikc/jpegview/assets/1808569/fd951d97-10c9-48c4-b7ac-b7c8ec8f6dd5)

**Comment by qbnu** [comment]
@jonatino The total pixels are greater than [`MAX_IMAGE_PIXELS`](https://github.com/sylikc/jpegview/blob/master/src/JPEGView/MaxImageDef.h#L47). @sylikc this can probably be increased as suggested in #307.
