### ISSUE TITLE
Hide the window title bar permanently

### ISSUE THREAD

**Issue by cherub0507** [sylikc/jpegview#188]
If hide the window title bar permanently could be optional, it would be very nice!

**Comment by sylikc** [comment]
This is planned as a startup option.

Then you could just unmap the key to toggle the borderless, and it'll be permanent 😅

**Comment by qixiaoshu** [comment]
> This is planned as a startup option.
> 
> Then you could just unmap the key to toggle the borderless, and it'll be permanent 😅

Excuse me, I canceled the keymap and selected Hide Window Title Bar in the right-click menu, but opened the next image, still with the title. What should I do?

**Comment by sylikc** [comment]
It's only planned. The option isn't available yet

**Comment by qixiaoshu** [comment]
Well, I misunderstood, looking forward to the new version.
