### ISSUE TITLE
Please add an option in JPEGView.ini to set HighQualityResampling for only downsampling

### ISSUE THREAD

**Issue by OCD-Man** [sylikc/jpegview#19]
Please consider adding an option in JPEGView.ini for the HighQualityResampling setting to be set to "downsample" so it only downlsamples when the image is zoomed out to less than a 1:1 ratio, and so upsampling is disabled when zooming in to more than 1:1 ratio.

The only use I have for zooming in to an image to larger than 1:1 is to be able to see the individual pixels to compare them to another differently compressed copy of the same image. But if I set HighQualityResampling to false, then when the image is zoomed out to smaller than 1:1, the resampling looks incredibly horrible.

I am trying to replace my usage of Windows 7 photo viewer with JPEGView, and photo viewer downsamples and doesn't upsample, which is the way I need it to be.

I hope you can add this option for me as well as fix the last issue I posted (#14) for your next update. With these 2 things fixed, I can feel comfortable setting JPEGView as my default image viewer, and I will just use something else for images with transparency until support for transparency is added to all of the image formats that don't yet support it.

**Comment by kevinfiol** [comment]
First off; thanks for picking up development on JPEGView. It has been my favorite photo viewer for Windows.

I do want to +1 this issue as I recently started working with pixel art and graphics, and while the `HighQualityResampling` set to `true` is wonderful for my photo collection, it makes viewing pixel art impossible. For the time being, I have switched to [qimgv](https://github.com/easymodo/qimgv) although it is noticeably slower than JPEGView.

**Comment by Hrxn** [comment]
Haven't tried this fork yet, but I see no change that would make it impossible to use a JPEGView.ini config file just like before?

Just use the context menu, configuration section, and open the .ini file from there (should be created automatically, if not existing yet).. then simply edit the file yourself, e.g. by setting `HighQualityResampling` to `false`, for example?

**Comment by kevinfiol** [comment]
> Haven't tried this fork yet, but I see no change that would make it impossible to use a JPEGView.ini config file just like before?
> 
> Just use the context menu, configuration section, and open the .ini file from there (should be created automatically, if not existing yet).. then simply edit the file yourself, e.g. by setting `HighQualityResampling` to `false`, for example?

Not sure on the technicals, but the issue is exactly that. If I set it to false, pixel art looks great, but photos look terrible. If set to true, vice versa.

This issue does not exist on qimgv or XnView Classic.

**Comment by Hrxn** [comment]
Ah, I know what you mean now. This is a feature request for a new resampling option that does not exist yet, neither in the fork, nor the original project.
Fair enough.
I mean, you can always toggle high quality resampling with <kbd>F3</kbd>, but I see how setting this automatically based on zoom level and image dimensions would be advantageous.

**Comment by sylikc** [comment]
Interesting... Let me look into this. I don't know if it's easy to add though.  The redrawing graphics routines are pretty complex.

**Comment by sylikc** [comment]
After the AVX2 bugfix, I've gotten a bit more familiar with the Resample routine...

I'm testing a `DownSample` addition for the next release

**Comment by sylikc** [comment]
@OCD-Man this is implemented in the branch right now... I need to do more testing to verify it actually works as expected.

Can you pull a [Development snapshot for resample-up-down branch](https://github.com/sylikc/jpegview/actions/workflows/build-release-x64.yml?query=branch%3Aresample-up-down) ([howto use Dev Snapshots](https://github.com/sylikc/jpegview/wiki/Dev-Snapshots)) for that branch to see if it works as expected?  Use the modified `HighQualityResampling` INI option to test.  Also if you have suggestions for text to describe the feature, let me know.  I tried the best I could to explain in the INI why one would want to use `DownSample` or `UpSample` only.

**Comment by alexgoulden** [comment]
Hey, just crossposting from #192 to confirm this works as expected and exactly what I was looking for, the description is accurate as is and I don't think it needs updating.

**Comment by sylikc** [comment]
I think this is resolved
