### ISSUE TITLE
bug for some webp will shows the result rotated by 90 degrees

### ISSUE THREAD

**Issue by snsnsjsn** [sylikc/jpegview#195]
hi , I have two png and translate into webp , but some webp will display not correctly

![image](https://github.com/sylikc/jpegview/assets/11435527/0c559628-bd78-4ab7-a2f6-78f3ae9799f9)

and the two.webp will rotate 90 degrees.

![image](https://github.com/sylikc/jpegview/assets/11435527/d8babc69-43f9-4102-b97e-eda6ea1832bd)

two.png is right, but two.webp will not 
![image](https://github.com/sylikc/jpegview/assets/11435527/1ae77f67-6e20-4ef8-8ad0-42ed6b5a0703)

**Comment by qbnu** [comment]
Can you upload the files?

**Comment by snsnsjsn** [comment]
> Can you upload the files?

hello ,  pls download the zip
[four pictures.zip](https://github.com/sylikc/jpegview/files/11632616/four.pictures.zip)

**Comment by qbnu** [comment]
I'm unable to replicate on the latest version. If it's still happening, can you post your JPEGView.ini and write the exact steps that cause this?
![webp-195](https://github.com/sylikc/jpegview/assets/93988953/c72de35c-8e8e-4246-8ded-f67cf5c06a1d)

**Comment by sylikc** [comment]
can't replicate in any recent version of JPEGView.  Reopen if still an issue
