### ISSUE TITLE
Please update the file encoding of RotationPanelCtl.cpp and EXIFDisplayCtl.cpp

### ISSUE THREAD

**Issue by oTnTh** [sylikc/jpegview#197]
utf-8 should work, otherwise I can't compile with Chinese version VS2022.

Thanks.

**Comment by sylikc** [comment]
I tried converting the files to UTF-8 and now I get a weird `Â°` instead of just the degrees symbol.  Not sure what I need to change to get that funky character not to show up... any ideas?

**Comment by oTnTh** [comment]
<img width="425" alt="Screenshot3" src="https://github.com/sylikc/jpegview/assets/92753/7719da33-2101-4388-bdbf-55d94205a9bc">

Does it look like this?

If so, you have done the converting. Those files are encoded with utf-8 now, you should open them with utf-8 encoding.

For example, VSCode, at the right-bottom of window.

![Screenshot](https://github.com/sylikc/jpegview/assets/92753/ad1f85a1-82e7-494a-857b-a0fe5aaf4a7b)

Click "Windows 1252", then "Reopen with encoding", choose utf-8.

Try this in settings.json of VSCode: `"files.autoGuessEncoding": true`

**Comment by sylikc** [comment]
I see it fine in code. It's just that when I compile it, in the interface I see the extra character

**Comment by oTnTh** [comment]
<img width="233" alt="Screenshot1" src="https://github.com/sylikc/jpegview/assets/92753/49b7926c-5258-4b43-a4bb-7f9c1a622f1d">


Do you mean this? That's my bad, try "UTF-8 with BOM", please.

It's probably because the compiler treat UTF-8 file as ANSI.

**Comment by sylikc** [comment]
Ah.  Ok, it works with BOM.  I'll check in the change after merging #202
