### ISSUE TITLE
Ability to add CTRL+C as a shortcut to close the app.

### ISSUE THREAD

**Issue by dubeg** [sylikc/jpegview#198]
Any way to add CTRL+C as a shortcut to close the app?
Since I'm already used to quickly closing Windows Explorer windows & browsers this way. :/

**Comment by sylikc** [comment]
You can map it with KeyMap.txt  ... So, for me closing windows is CTRL+W... isn't CTRL+C for copy and pasting??

**Comment by dubeg** [comment]
Yes you're right, I'm sorry :s
