### ISSUE TITLE
JPegview automatically changes the color of the original image

### ISSUE THREAD

**Issue by blackshu617** [sylikc/jpegview#199]
I tried opening this image with other software, the result is the color does not change
but when i open this image with JPegview the result is that the color of this image is changed. This is a comparison example when I open the image with JPegview and windows photo viewer: https://i.imgur.com/VYLgBBh.jpeg

this is the original image: https://i.imgur.com/mXwAP9m.jpg

**Comment by qbnu** [comment]
Set `UseEmbeddedColorProfiles=true` in your JPEGView.ini file.

**Comment by blackshu617** [comment]
> Set `UseEmbeddedColorProfiles=true` in your JPEGView.ini file.
it's worked, thank you bro
