### ISSUE TITLE
Feature request: next/prev photo keeping zoom

### ISSUE THREAD

**Issue by kiawizard** [sylikc/jpegview#200]
FastPictureViewer has a very useful feature: I double-click to zoom-in (the same behavior in jpegview), then do not release mouse button and press right/left arrows on keyboard to go to next/previous photo keeping zoom level and position. This helps to identify which of multiple similar shots is less motion-blurry and delete other shots. Please implement this in jpegview if possible

**Comment by sociofall** [comment]
![изображение](https://github.com/sylikc/jpegview/assets/67294769/4e04fec2-5437-4724-8943-450b4db82f0e)

**Comment by kiawizard** [comment]
You mean changing this setting every time I need to compare two photos?

**Comment by sociofall** [comment]
> You mean changing this setting every time I need to compare two photos?

i mean is there any sense to keep it false?

**Comment by sociofall** [comment]
oh, i don't see you want also position. sorry

**Comment by sylikc** [comment]
I guess it would be possible, but let me investigate further to see exactly how difficult this might be.  Holding the same zoom and position may seem easy in theory, but that's not how the image rendering happens...

**Comment by Hrxn** [comment]
Isn't there a default key for this? F3? F4?
Sorry, can't check right now, not at an PC with JPEGView 😄

**Comment by kiawizard** [comment]
Hrxn, right you are, pressing F4 toggles the same mode (without having to hold mouse button). Will get used to it, thank you for the hint!
