### ISSUE TITLE
windows binaries pls

### ISSUE THREAD

**Issue by gonzalezvaguiner** [sylikc/jpegview#21]
deaf ppl need

**Comment by Pentaphon** [comment]
The windows binaries are in the releases. The zip files = binaries. This is a Windows-only application.

**Comment by sylikc** [comment]
JPEGView doesn't require installation, the binaries are in the zip file.  Unless you're asking about an installer...

**Comment by Pentaphon** [comment]
> Unless you're asking about an installer...

I hope you never do an installer. All I want is jpegxl support in the future.
