### ISSUE TITLE
Ability to add Frameless/Borderless to INI File

### ISSUE THREAD

**Issue by zelosleone** [sylikc/jpegview#229]
I'm aware there is a shortcut key for this view setting, but i honestly would prefer if it was my default. It's a waste to use the shortcut everytime after i open a picture, i just want it to be open in a borderless/frameless state. Thank you.

**Comment by sylikc** [comment]
It's a duplicate feature request, but just out of curiosity, what's your use case for having a borderless window on startup.  Are you moving it with the ALT+LCLICK or just having it off in the corner somewhere?

**Comment by zelosleone** [comment]
> It's a duplicate feature request, but just out of curiosity, what's your use case for having a borderless window on startup. Are you moving it with the ALT+LCLICK or just having it off in the corner somewhere?

Both, to be honest. I am using it purely for aesthetics sometimes and other times via alt+left click.
