### ISSUE TITLE
Exif data loss after lossless transformations.

### ISSUE THREAD

**Issue by pelsta** [sylikc/jpegview#245]
After lossless image transformations (left rotation, cropping, etc.), exif data are not saved to the file.
This has been happening since version 1.2.45.0.

**Comment by sylikc** [comment]
hmm 🤔... i did a diff and nothing changed that would affect that in 1.2.45 vs 1.1.44 ... 

https://github.com/sylikc/jpegview/compare/v1.1.44...v1.2.45

but I did a simple test with the old version and it definitely broke in 1.2.45

**Comment by sylikc** [comment]
I examined the code paths to get to the TurboJPEG call... nothing changed, and the library didn't change in 1.2.45 ... I'll have to look into it more deeply 🤦‍♂️

**Comment by sylikc** [comment]
@qbnu would you have any ideas what changed that could've broke this feature?  I've been staring at it for a few hours and nothing stands out as to why it worked in 1.1.44 but not in 1.2.45

**Comment by qbnu** [comment]
@sylikc caused by https://github.com/sylikc/jpegview/commit/0104c93073395178514b9cfe59619bfb6eea3f3d

**Comment by Hrxn** [comment]
Time to move to libjpeg-turbo v.3.0.0?
