### ISSUE TITLE
[FEAT] Association of .jfif filetype

### ISSUE THREAD

**Issue by Smgit5** [sylikc/jpegview#251]
Please bring the support to open .jfif filetype.

Screenshot:
![image](https://github.com/sylikc/jpegview/assets/94289238/9a169de1-8bbf-4499-bc5e-043160973adc)

**Comment by qbnu** [comment]
As a temporary workaround you could add `*.jfif` to `FileEndingsRAW` or `FilesProcessedByWIC`, and the file will get detected as a JPEG.

**Comment by Smgit5** [comment]
Thanks! This workaround worked.
