### ISSUE TITLE
Customisable keyboard shortcuts

### ISSUE THREAD

**Issue by SpitFire-666** [sylikc/jpegview#266]
I'd like to be able to zoom in and out using +/= and - keys. 

We can already move around zoomed images using Shift+Arrow keys which is nice, I'd just like to be able to zoom with the keyboard too.

Another option is to let us set our own shortcuts in the INI file.

Cheers

**Comment by Hrxn** [comment]
You already can..
Simply make the changes you wish to `KeyMap.txt`.

**Comment by sylikc** [comment]
(Thanks for the earlier reply @Hrxn .)

@SpitFire-666 look at the `KeyMap-README.html` in the JPEGView directory for instructions on how to create the KeyMap.txt
