### ISSUE TITLE
"SingleInstance=false" option is invalid.

### ISSUE THREAD

**Issue by DeepTulip** [sylikc/jpegview#272]
If the first process loads an image larger than the screen, it will display it in a full-screen window. Then subsequent processes that load it will still load it in this window.

This also involves another issue, I would like to open all images in full screen mode, but the reality is that JPEGView gives up on full screen when it finds an image smaller than the screen.

win-10 64 
v1.3.46

**Comment by Hrxn** [comment]
In `JPEGView.ini`

```
ShowFullScreen=true
```

Not sure what you describe here, but I never encountered it.
Maybe you've messed up your .ini file somehow?
