### ISSUE TITLE
option to disable image smoothing -- for viewing sprites

### ISSUE THREAD

**Issue by lawleagle** [sylikc/jpegview#286]
when I zoom in or out, for a second I see the sprite as I want to see it, then the program takes over and smooths the sprite for me. I suppose it's good to do that on actual photos, but not on sprites.

alas, I think an option to disable that smoothing would make this the best sprite viewer on the internet

**Comment by Hrxn** [comment]
Also:

Try this setting in your `JPEGView.ini`:

```ini
Sharpen=0.0
```
