### ISSUE TITLE
how  to set up to delete without confirm?

### ISSUE THREAD

**Issue by aohanhongzhi** [sylikc/jpegview#309]

**Comment by thradya** [comment]
Open keymap.txt.default and edit "Del" mapping as follows:

Del                     IDM_MOVE_TO_RECYCLE_BIN

That's it. That is of course if you're not using recycle bin.

**Comment by sylikc** [comment]
@aohanhongzhi you can also set up the setting in JPEGView.ini https://github.com/sylikc/jpegview/blob/efd55a1a0b922bd7274c1d44717dac4104bb0fa3/src/JPEGView/Config/JPEGView.ini#L566-L570

As @thradya mentioned and it's shown above, map it to `IDM_MOVE_TO_RECYCLE_BIN`

**Comment by MSAfotografia** [comment]
It worked, thank you!!
https://github.com/user-attachments/assets/896ccf73-7778-448f-a2e3-f6675d8dd120
