### ISSUE TITLE
animated webp images not playing?

### ISSUE THREAD

**Issue by Owyn** [sylikc/jpegview#33]
[example_95977880_ugoira1920x1080.zip](https://github.com/sylikc/jpegview/files/7994673/example_95977880_ugoira1920x1080.zip)

webpCodec = libwebp
webpParam = -lossless 0 -q:v 90 -loop 0 -vsync 2 -r 999

source: https://www.pixiv.net/en/artworks/95977880
encoder: pixivutil2 -> ffmpeg

**Comment by sylikc** [comment]
I can confirm it doesn't work but can't seem to trace to where it fails.

@KrokusPokus , you did some webp work adding the transparency... would you have a chance to take a look if this is a simple bug or something deeper?

**Comment by KrokusPokus** [comment]
From what I have seen, webp animation is not implemented in the interface to the external library (`webp\webp.cpp`) right now, even though functionality seems to be there in the library itself (search `demux.h` for the term `animation` and you'll see what I mean).
