### ISSUE TITLE
Incorrect  orientation of HEIC photos (1.3.46)

### ISSUE THREAD

**Issue by aleks-ko89** [sylikc/jpegview#335]
Photos from my iPhone 8 (iOS 16.7) on version 1.3.46 (x64) are displayed in horizontal orientation.
On version 1.2.45 (x64) the file orientation was displayed correctly.
I attach an example file (in zip archive).
[IMG_5745.zip](https://github.com/user-attachments/files/17003296/IMG_5745.zip)
OS Windows 10 Pro 22H2 x64

**Comment by qbnu** [comment]
Fixed by #304

**Comment by sylikc** [comment]
(I've been pending a release since there's so many changes... but I've also been applying for a binary signing certificate hoping that will come through, but i may just have to release without it being signed)
