### ISSUE TITLE
Add an option for "Open image location"/"Open folder path".

### ISSUE THREAD

**Issue by Illegal-Services** [sylikc/jpegview#34]
Add an option for "Open image location"/"Open folder path".

In the right clic context menu?

**Comment by sylikc** [comment]
Thanks for submitting a feature request.  It's now available in v1.0.39!

**Comment by sylikc** [comment]
Release is now available https://github.com/sylikc/jpegview/releases/tag/v1.0.39

**Comment by Illegal-Services** [comment]
Thank you SO much!

I really appreciate it, and it will save me a lot of time now (from searching the file manually) ... :)
