### ISSUE TITLE
About

### ISSUE THREAD

**Issue by Georgiy-Timoshin** [sylikc/jpegview#48]
add a github link to the "about" window
![Безымянный](https://user-images.githubusercontent.com/38873082/159147000-40d57a37-c176-4064-b003-7d852c263c4b.png)

**Comment by sylikc** [comment]
Good catch. I'll change that in the next release. Thanks!

**Comment by sylikc** [comment]
I rolled this change into a branch I'm currently working on.  Thanks!

I also have to update the readme*.html at some point though ...
