### ISSUE TITLE
Option to hide titlebar

### ISSUE THREAD

**Issue by kiwijam** [sylikc/jpegview#5]
It would be nice to have a setting to hide JPEGView's titlebar by default.

**Comment by sylikc** [comment]
You mean hide it even when not in fullscreen?  then how would you move the window around?

**Comment by kiwijam** [comment]
When not in fullscreen, yes. I don't really need controls to move the window. But maybe alt-Lclick/Rclick? It would be awesome if at some point JPEGView's own minimise/restore/close buttons could be extended to be a draggable titlebar that can be hidden until hovered over!

![image](https://user-images.githubusercontent.com/7322709/118632887-2ca52380-b7d1-11eb-9a8e-82c9c75fb81a.png)
CWndButtonPanel?

**Comment by c-sanchez** [comment]
Yes, a borderless window mode might be nice, normally this type of image viewer allows you to move the window by clicking anywhere in the image window, however jpegview has a selector inside.

So, a option can be enable the window moving with some key + mouse click, like **alt+left mouse button**
Other way I think can be automatically display the title bar when hovering the mouse over the top of the window.

This are the Window option in Honeyview
![](https://i.ibb.co/rZWT7L3/Honeyview-window-options.jpg)
![]()
![]()

https://i.ibb.co/Cbmjpz5/Honeyview-normal-window.jpg
https://i.ibb.co/Lt1rT28/Honeyview-no-titlebar-window.jpg
https://i.ibb.co/84Y8LqP/Honeyview-borderlesss-windows.jpg

**Comment by sylikc** [comment]
As an option, I'll think about it.  I usually just use fullscreen if I want the border/title bars to go away heh

**Comment by OCD-Man** [comment]
I never thought of having a window without a titlebar. If you make this option available, I vote for automatically displaying the title bar when hovering the mouse over the top of the window.

One of JPEGView's purposes is to be able to show as much of the image as possible. So this idea would actually be a good update for JPEGView, and should even be an option in the right click menu.

**Comment by OCD-Man** [comment]
I never thought of having a window without a titlebar. If you make this option available, I vote for automatically displaying the title bar when hovering the mouse over the top of the window.

JPEGView is designed to show as much of the image as possible. So this idea would actually be a great update for JPEGView, and should even be an option in the right click menu.

**Comment by sylikc** [comment]
I just took some time to try to get this feature working. It's a bit glitchy, but please check the release artifacts to see if this is the way you'd want it. Further comments on PR please.
