### ISSUE TITLE
JPEGView64 portable will be unresponsive when zooming in and dragging images.

### ISSUE THREAD

**Issue by Azvuk** [sylikc/jpegview#53]
After zooming in on the image and dragging it a few times, JPEGView64 portable becomes unresponsive. Attached is the screenshot.

This is the case on both Win7 64-bit and Win10 64-bit.

JPEGView32 portable does not have this issue.

My Computer：
CPU: i7 4770K
Memory: 32G
GPU: GeForce RTX 2060 super

![Snipaste_2022-04-09_17-15-01](https://user-images.githubusercontent.com/55695461/162565178-bd1d1d80-f54b-4eb2-9d0b-0264d2b06c77.jpg)
.

**Comment by sylikc** [comment]
Is it on a particular image or all images? Or a certain image type?

First thing I'd try is disabling AVX. There's another issue open about possibly some AVX problem on big images

**Comment by sylikc** [comment]
Might possibly be related to issue #10

**Comment by Azvuk** [comment]
> 

I tested it on jpg, png, gif, no matter what type, no matter how many pixels, the issue allways occurs.

**Comment by Azvuk** [comment]
> Might possibly be related to issue #10

Thank you for your help. I changed the CPUType to SSE and the HighQualityResampling to false. The issue did not reoccur.

Strangely, this issue only occurs with JPEGView64. It does not occur even if the default ini file is unchanged when use JPEGView32.

**Comment by sylikc** [comment]
It might be specific code... The AVX logic might not trigger in 32-bit... I need to investigate the code to be sure.

So basically, it should speed up for most users, but for huge images, the AVX code crashes.

**Comment by Mack-Magic** [comment]
I was having the same issue with any large image (about 4k resolution or higher) and managed to make it stop by overriding the program's scaling method in Windows 10 from application to system. Doesn't seem to have affected image quality at all and I can zoom around on large images with no problem now.

**Comment by sylikc** [comment]
> I was having the same issue with any large image (about 4k resolution or higher) and managed to make it stop by overriding the program's scaling method in Windows 10 from application to system. Doesn't seem to have affected image quality at all and I can zoom around on large images with no problem now.

Oh interesting... so, how exactly is that done?  Is that through compatibility options or somewhere else in Win10?

**Comment by sylikc** [comment]
@Azvuk @Mack-Magic can you test the latest development snapshot and see if the workaround that I put in fixes the freezing?

Download the latest 64-bit dev snapshot https://github.com/sylikc/jpegview/wiki/Dev-Snapshots#links and report back, thanks!

**Comment by sylikc** [comment]
v1.2.45 has been released that fixes this issue.  You should be able to undo the changes to HiDPI settings, and CPUType/HighQualityResampling INI options.  Please reopen issue if crash/freeze still happens.

**Comment by Azvuk** [comment]
Sorry for the late reply. After testing, I found that the new version solved the problem, the issue did not recur, thank you very much for your effort. @sylikc
