### ISSUE TITLE
New menu "Open containing folder in Explorer" not localized

### ISSUE THREAD

**Issue by LaurentGrenet** [sylikc/jpegview#58]
This new menu, coming with v1.0.39, is not translated in localized versions.
Here is my proposal for french : Afficher le fichier dans l'explorateur

**Comment by sylikc** [comment]
Ok, I'll put that into the next release.  Yeah I added it without localizing

**Comment by LaurentGrenet** [comment]
New release 1.1.41has been delivered today, January 1st 2023, and unfortunately, this string is still missing in localisation files....
Pls don't forget it in next release ;-)
