### ISSUE TITLE
.webp animated Bug

### ISSUE THREAD

**Issue by Mcpyore** [sylikc/jpegview#61]
Hi! I downloaded some .webp image, they give error when i try to open them ("file name.webp" could not be read). I think the problem has something to do with the fact the images are animated (gifs with webp format). They work fine in Firefox for example.

**Comment by sylikc** [comment]
this is probably related to issue #33 .  webp animated images aren't implemented yet

**Comment by Mcpyore** [comment]
> this is probably related to issue #33 . webp animated images aren't implemented yet

Oh sorry, didnt see that. No problem then
