### ISSUE TITLE
"Open with" or "Edit with" feature

### ISSUE THREAD

**Issue by MysisR** [sylikc/jpegview#63]
This tool is perfect and fast, except the only 1 thing that lacks of, in my opinion (and that for now makes me stick to the default Windows one): to open the image with a given application, from the right click menu (or a button or anything). 
Like, example:    Edit Image > [List of selected possible applications to use], or even, "Edit Image" only, and it opens a default selected one, with one click less. I edit images a lot, many per day, so I use this feature continuously.

**Comment by sylikc** [comment]
So, for this feature, would you like a popup of the system edit menu?  Or configure specific apps in the INI to do an edit?  And perhaps configure with a hotkey?

Btw, to do it via INI and configure it with a hotkey is already possible right now... You can add a UserCmd to launch the edit app of your choice and then assign a hotkey.  This could allow you to edit with whatever app you most use, or assign multiple keys to different apps.

**Comment by pedjas** [comment]
I vote for system menu for Edit with and Open with as I use two or three different applications depending what I need to do with the image.

**Comment by sylikc** [comment]
So, this feature already exists.  While it's not the system menu, there's a way to get it to open with the apps you want

Right Click > Settings/Admin > Manage 'Open image with' menu...

Then create some entries, and you will see a new menu right under "Open Image"

**Comment by sylikc** [comment]
closing this issue as resolved (already implemented) and stale
