### ISSUE TITLE
HEIC Images support

### ISSUE THREAD

**Issue by RuslanKim** [sylikc/jpegview#67]
Could you please add HEIC Images support? 
More and more images in this format from Android & iOS devices...

**Comment by RuslanKim** [comment]
Or ...  does WIC should not help us with?

**Comment by RuslanKim** [comment]
https://www.microsoft.com/store/productId/9PMMSR1CGPWG - this component does help at all :(

**Comment by sylikc** [comment]
I thought there was a discussion awhile ago about HEIC with WIC.  I'd have to go looking for it..

**Comment by sylikc** [comment]
@RuslanKim please look at the solution in https://github.com/sylikc/jpegview/issues/4#issuecomment-843047147 While JPEGView doesn't directly support HEIC, it is supported by the flag `FilesProcessedByWIC`

**Comment by sylikc** [comment]
HEIC support is coming in #109
