### ISSUE TITLE
Zooming with Thinkpad TrackPoint gets "stuck" at 100%

### ISSUE THREAD

**Issue by lord-ne** [sylikc/jpegview#68]
If an image is initially zoomed to less than 100% (such as if it is set to open in windowed mode), scrolling with the mouse wheel will get you to 100% zoom. Even if I stop scrolling and then start scrolling again, it still won't go past 100% zoom. Only after clicking and dragging a bunch does it "randomly" decide to go past 100% when I scroll more.

Here's a video showing what I mean. I have a program showing my keypresses in the bottom right for demonstration proposes; when the number is increasing, that means I am currently scrolling the mouse wheel up/down. 

https://user-images.githubusercontent.com/34069872/177727411-a1ac982c-f99e-4f89-b7e7-96f203c9d840.mp4

You can see that it scrolls in normally until it hits 100%, but won't scroll further. I stop scrolling and start again, but it still won't scroll further. At around 15 seconds I try scrolling down to zoom out, but that also doesn't work. I try clicking and dragging then scrolling again, which doesn't work, but then I click and drag again and then it works.

**Comment by sylikc** [comment]
@lord-ne are you still having problems with this?  I haven't ever been able to reproduce this problem.

What type of mouse are you using and is there custom software that interprets the window before doing something?  Like it's actually trying to "scroll" the window?

**Comment by lord-ne** [comment]
I was using the middle button on a Thinkpad. Is you hold down that button and move the red mouse, it acts as trying to scroll the window up or down.
![image](https://user-images.githubusercontent.com/34069872/219375771-a162fb0b-4cd3-48f3-b10f-6101841bc097.png)

---

I just retested with a normal USB mouse. When I scroll the mouse wheel, it will still briefly get stuck at 100% as long as I continue scrolling without taking my finger off of the mouse  wheel. However it gets "unstuck" as soon as I even briefly lift my finger off the mousewheel. Since it becomes "unstuck" if you even very briefly stop moving the scroll wheel, it's not very noticeable in this case. 


https://user-images.githubusercontent.com/34069872/219377130-c5e161e1-9063-490d-ad82-e20675402088.mp4

**Comment by sylikc** [comment]
Unfortunately that'll be a bit harder to debug...

I've owned a thinkpad before, and those software emulated mouse functions can interact strangely with certain apps.  The mouse filter drivers that are installed affect USB mice as well iirc.  Anyhow, I wouldn't really know how to even look into it.

Thanks for posting the videos though to show the behavior.  It definitely looks jumpy from your videos but I can't reproduce it at all.

So what the middle scroll thingie on the Thinkpad is probably doing is that... it's polling JPEGView and seeing if there's anything on the window controls to scroll.  It figures out there isn't anything (no scrollbars anywhere in the client area) and so it probably is falling back to some type of scroll emulation.  That stuff is hit and miss on non-standard windows like image viewers.  I used to have all types of problems scrolling through specialized applications, but that was a long time ago lol.

**Comment by lord-ne** [comment]
Fair enough. Although I think the fact that I was able to get something similar to happen at 100% with a regular mousewheel (it's just less annoying) means that there's at least something more going on.

**Comment by lord-ne** [comment]
I was also able to replicate the issue with an [AutoHotkey](https://www.autohotkey.com/) script (v2), if you're familiar with that.

```AutoHotkey
#Requires AutoHotkey v2
#SingleInstance force
KeyHistory 0

; Clicking the wheel a bunch of times gets stuck
1:: {
    Send("{WheelUp 100}")
}

; Adding a delay between the clicks makes it not get stuck
2:: {
    Send("{WheelUp 100}")
    Sleep(1000)
    Send("{WheelUp 100}")
}

; But if the delay is too short, it still gets stuck
3:: {
    Send("{WheelUp 100}")
    Sleep(100)
    Send("{WheelUp 100}")
}
```

**Comment by sylikc** [comment]
I looked at the code, the hard stop at 100% is intentional
https://github.com/sylikc/jpegview/blob/80f117b0c117274861a15c876416078d0865692e/src/JPEGView/MainDlg.cpp#L2595-L2597

**Comment by sylikc** [comment]
not all mice have fine control, so the intention is that it will always make a stop at 100% regardless of what scroll factor your mouse causes

**Comment by sylikc** [comment]
You can also test this behavior with the + and - keys... it will stop at 100%

**Comment by lord-ne** [comment]
Thank you for the help. I commented out the three lines you referenced and compiled, and it gives me the behavior I want. Interestingly, there is actually still a small stop at 100%, but only if you're zooming in very slowly (which is a good thing in my opinion). 

Do you think it would be worth adding an option to disable the hard stop, for people who have various non-standard scrolling setups?

**Comment by sylikc** [comment]
It's an interesting idea... so I put it in.  100 is default, 0 to disable.  Some people might want to pause at a different percentage... so I made it user changeable.

**Comment by RndUsr123** [comment]
Any chance the preference can be changed to disable the 100% snap previously mentioned too?
