### ISSUE TITLE
I would love to see this project on Linux. Is it possible to port it?

### ISSUE THREAD

**Issue by NightFlexer** [sylikc/jpegview#69]

**Comment by rorgoroth** [comment]
I know this doesn't answer your question but have you tried any alternatives? When I used Linux years ago Viewnior was very good, that's why I chose jpegview because it is fairly similar (at least to my memory) - I'm not sure if it still developed or not.

**Comment by sylikc** [comment]
@NightFlexer I would say it's not possible to port this to Linux.  This has and is known for being one of the quicker viewers for Windows only.  The whole codebase is aimed towards win32 specific APIs and all (think popup menus, dialogs, etc), so it would probably be very difficult or nearly impossible (without a complete rewrite) to port to Linux.

I would suggest @rorgoroth 's recommendations of looking into an alternative viewer.  There are many FOSS viewers to choose from on Linux.

**Comment by NightFlexer** [comment]
> I would suggest @rorgoroth 's recommendations of looking into an alternative viewer. There are many FOSS viewers to choose from on Linux.

Thank you for the answer
