### ISSUE TITLE
How to hide this title bar?

### ISSUE THREAD

**Issue by TheCodeverse** [sylikc/jpegview#75]
![Screenshot 2022-08-23 143005 title](https://user-images.githubusercontent.com/37426761/186091045-78a5f113-9011-4526-b24e-84ec74888ab4.jpg)

**Comment by OCD-Man** [comment]
This was already mentioned as a request to add an option to remove title bar in issue #5 . I still think it would be a great option to configure in the ini file and to put in the right click menu.

**Comment by OCD-Man** [comment]
I was just thinking that the Title Bar disappears when setting the window to full screen by pressing F11 (or right clicking the picture and going to the Zoom submenu to choose Full Screen Mode).

Maybe that works for you for now.

**Comment by TheCodeverse** [comment]
> 

Thanks. I only use full screen mode when I'm concentrating on viewing a large number of images. Usually I just use windowed mode so it doesn't cover my screen all the way.

**Comment by 4hench** [comment]
@sylikc please add this feature want it so bad, disable the selector as an option so you then can move around the picture with ease

**Comment by sylikc** [comment]
I just took some time to try to get this feature working.  It's a bit glitchy, but please check the release artifacts to see if this is the way you'd want it.  Further comments on PR please.
