### ISSUE TITLE
PNG Metadata support

### ISSUE THREAD

**Issue by SMUsamaShah** [sylikc/jpegview#77]
Hi, Thanks for keeping jepgview up to date. Was using a tool which saves some data exif of the pngs it generates but jpegview does not support it.
Can you please consider adding support for PNG metadata since PNGs now have metadata.

- http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf
- https://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_PNG_files

**Comment by sylikc** [comment]
Looks complex... I was reading the specification and it shows that text can even be compressed in metadata.

**Comment by sylikc** [comment]
closed by https://github.com/sylikc/jpegview/pull/213 , included in 1.3.46 release
