### ISSUE TITLE
Cannot open webp files

### ISSUE THREAD

**Issue by gregzaal** [sylikc/jpegview#78]
I believe webp is meant to be supported now, but I still get "The file xyz.webp could not be read!" errors when opening any webp file.

Example file:
[thumbnail.zip](https://github.com/sylikc/jpegview/files/9441842/thumbnail.zip)

**Comment by sylikc** [comment]
@gregzaal please try https://github.com/sylikc/jpegview/issues/4#issuecomment-843047147

**Comment by gregzaal** [comment]
Do you mean adding webp to the config `FilesProcessedByWIC=*.wdp;*.hdp;*.jxr;*.webp` ?

This doesn't seem to help.

**Comment by OCD-Man** [comment]
I know there is no problem opening webp files.

So the first thing I did was to open the file you attached in your post in a hex editor to look at the text portion of the hex editor window to see if it is actually a webp file.

The header clearly says it is a png file.

So rename your file as PNG and it will open.

Normally if you rename a file to a different extension, the program just detects what king of file it is from the header or whatever, not from the file extension which is just to tell the operating system which program should open the file, which can be seen by changing this file extension to .jpg. But webp has it's own dll file which makes me think that webp support is more of an addon to the program. Still JPEGView should read the header of the file to determine if it is webp before processing it as webp, even it initially JPEGView attempts to open it as webp based on the file extension, if that is even possible to do in this circumstance.

But that should be put in a to do list, and as for this issue, I guess it can be closed.

**Comment by LaurentGrenet** [comment]
Hello all, (and in particular hello @sylikc )

what is VERY surprising with Webp management by JPEGView is that if we have a look on file provided by @gregzaal in its initial message just above, and about which one @OCD-Man says it's actually a png file (according what we can see as its actual content) is the fact that JPEGView is able to open it **in any case except if its extension is .webp !**
If you rename the file as [anything].jpeg, [anything].png, [anything].bmp, or even no [anything].[anyextension] except webp, or even no extension at all,  JPEGView opens it succesfully ! Only if it's named [anything].**webp** that JPEGView fails opening it !
Strange, no ?

And on the other hand, all files "natively Webp" (ie. that are proposed to be stored with a .webp extension when right-click + save image as", eg. the one proposed in https://en.wikipedia.org/wiki/WebP) that I have downloaded from the WEB have **all been correctly opened by JPEGView**... even when named *.webp (and also if renamed *.png, *.bmp, *.jpg, *.[whateveryouwant] )

**Very** strange, no ?

**Comment by sylikc** [comment]
Closed by #93
