### ISSUE TITLE
[Question] Is this fork...dead?

### ISSUE THREAD

**Issue by vaguiners** [sylikc/jpegview#86]
Although there are "hacks" to install store extensions on windows 10 ltsc, I prefer not to do tricks. As Jpegview relies on WIC, a bad practice, my only option will be to switch to better alternative (not better than jpegview but better alternative) qview

Please fix #4

**Comment by sylikc** [comment]
not quite dead... I've been a bit strapped for time at the moment... life things.  Though adding support for some direct codecs would require some other image developer help.
