### ISSUE TITLE
Always on Top

### ISSUE THREAD

**Issue by madnessandvision** [sylikc/jpegview#87]
First to all, thanks for the amazing work. I was wondering if there is an "always on top" mode for this viewer or if you guys are planing to add as a feature. This is a very useful tool for designers or artists that uses references a lot

**Comment by sylikc** [comment]
I guess it could be added as an option... it's not there right now though.  Are you using it on one monitor only?

**Comment by sylikc** [comment]
I'm adding this feature in my current branch, please test it thanks
