### ISSUE TITLE
Easier access to resize option

### ISSUE THREAD

**Issue by pedjas** [sylikc/jpegview#88]
The most frequent option I do with images is resizing them. I would like to have that option easier to access without need to dig through menu. Best position is in button menu.

Hotkey assigned to resize option would be great to.

**Comment by sylikc** [comment]
Ok, I just added an entry to KeyMap.txt.  In the next release, you will be able to bind this to a key by editing KeyMap.txt.  It will give you quick access to the `Transform image > Change size...` option
