### ISSUE TITLE
Option to set crop mode to same ratio as image that is cropped

### ISSUE THREAD

**Issue by pedjas** [sylikc/jpegview#89]
When cropping image, I usually need to keep the same ratio of the image, just want to cut out some parts. It would be good to have that option.

Also, when cropping is activated, cropping options could be made available for easy access to avoid digging through menus.

**Comment by sylikc** [comment]
Cropping to image aspect ratio has been added in ffa658ad46b99d3c2a0738c23a0cd59ecbac58c6 .  When cropping is active, you can right click on the image, and it will show the cropping options instead of the default popup menu
